Repository Gachon-CS-Study/CS-Study, pull requests merged in 2024-09, with the labels that each got.

#9 [컴퓨터 구조] 입출력 시스템
  컴퓨터 구조/images/입출력 시스템/DMA(1).png
  컴퓨터 구조/images/입출력 시스템/DMA(2).png
  컴퓨터 구조/images/입출력 시스템/DMA(3).png
  컴퓨터 구조/images/입출력 시스템/DMA(4).png
  컴퓨터 구조/images/입출력 시스템/인터럽트 기반 입출력(1).png
  컴퓨터 구조/images/입출력 시스템/인터럽트 기반 입출력(2).png
  컴퓨터 구조/images/입출력 시스템/인터럽트 기반 입출력(3).png
  컴퓨터 구조/images/입출력 시스템/입출력 버스(1).png
  컴퓨터 구조/images/입출력 시스템/입출력 버스(2).png
  컴퓨터 구조/images/입출력 시스템/프로그램입출력(1).png
  컴퓨터 구조/images/입출력 시스템/프로그램입출력(2).png
  컴퓨터 구조/images/입출력 시스템/프로그램입출력(3).png
  컴퓨터 구조/입출력 시스템.md
Labels: 컴퓨터 구조, 민혁

#10 [컴퓨터 구조] 컴퓨터의 구성
  컴퓨터 구조/컴퓨터의 구성.md
Labels: 컴퓨터 구조, 지원

#11 [컴퓨터 구조] 메모리 계층 구조
  컴퓨터 구조/images/메모리 계층 구조/image-1.png
  컴퓨터 구조/images/메모리 계층 구조/image-2.png
  컴퓨터 구조/images/메모리 계층 구조/image-3.png
  컴퓨터 구조/images/메모리 계층 구조/image-4.png
  컴퓨터 구조/images/메모리 계층 구조/image.png
  컴퓨터 구조/메모리 계층 구조.md
Labels: 컴퓨터 구조, 승원

#12 [컴퓨터 구조] 중앙처리장치(CPU) 작동 원리
  .github/pull_request_template.md
  .gitignore
  컴퓨터 구조/images/중앙처리장치(CPU) 작동 원리/ALU 구조.png
  컴퓨터 구조/images/중앙처리장치(CPU) 작동 원리/CPU 동작 과정.png
  컴퓨터 구조/images/중앙처리장치(CPU) 작동 원리/CPU의 구성요소.png
  컴퓨터 구조/images/중앙처리장치(CPU) 작동 원리/레지스터 구조.png
  컴퓨터 구조/images/중앙처리장치(CPU) 작동 원리/제어장치 구조.png
  컴퓨터 구조/중앙처리장치(CPU) 작동 원리.md
Labels: 컴퓨터 구조, 현수

#13 [컴퓨터 구조]패리티비트&해밍코드
  .idea/.gitignore
  .idea/CS-Study.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  컴퓨터 구조/images/0.패리티비트.png
  컴퓨터 구조/images/1.패리티비트_예제.png
  컴퓨터 구조/images/2.해밍코드_패리티비트.png
  컴퓨터 구조/images/3.해밍코드_패리티비트위치.png
  컴퓨터 구조/images/4.해밍코드_예제_송신.png
  컴퓨터 구조/images/5.해밍코드_예제_수신.png
  컴퓨터 구조/패리티비트_해밍코드.md
Labels: 컴퓨터 구조, 은정

#14 [컴퓨터 구조] 캐시 메모리
  컴퓨터 구조/images/Direct Mapped Cache.png
  컴퓨터 구조/images/l1,l2,l3.png
  컴퓨터 구조/images/l1,l2,l3의 비교.png
  컴퓨터 구조/images/병목 현상.png
  컴퓨터 구조/images/캐시 히트 캐시미스.png
  컴퓨터 구조/images/하드디스크와 램.png
  컴퓨터 구조/캐시 메모리.md
Labels: 컴퓨터 구조, 성열

#15 [컴퓨터 구조] 고정 소수점 & 부동 소수점
  컴퓨터 구조/images/고정 소수점 & 부동 소수점/그림1.png
  컴퓨터 구조/images/고정 소수점 & 부동 소수점/그림2.png
  컴퓨터 구조/images/고정 소수점 & 부동 소수점/서론.png
  컴퓨터 구조/images/고정 소수점 & 부동 소수점/진수변환(1).png
  컴퓨터 구조/images/고정 소수점 & 부동 소수점/진수변환(2).png
  컴퓨터 구조/고정 소수점 & 부동 소수점.md
Labels: 컴퓨터 구조, 지영

#30 [운영체제]IPC
  운영체제/IPC.md
  운영체제/images/1.ipc.png
  운영체제/images/2.pipe.png
  운영체제/images/3.messageQueue.png
  운영체제/images/4.socket.png
  운영체제/images/5.sharedMemory.png
Labels: 은정, 운영체제

#29 [운영체제] 시스템 콜
  운영체제/시스템 콜.md
Labels: 성열, 운영체제

#28 [운영체제] PCB와 Context Switching
  운영체제/PCB와 Context Switching.md
Labels: 지원, 운영체제

#26 [운영체제] 인터럽트
  .idea/.gitignore
  .idea/CS-Study.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  운영체제/images/인터럽트 과정.png
  운영체제/images/커널유저모드.png
  운영체제/인터럽트.md
Labels: 현수, 운영체제

#25 [운영체제] 프로세스와 스레드
  운영체제/images/프로세스와 스레드/멀티쓰레드.png
  운영체제/images/프로세스와 스레드/쓰레드.jpeg
  운영체제/images/프로세스와 스레드/프로그램과 프로세스.png
  운영체제/images/프로세스와 스레드/프로세스.jpeg
  운영체제/프로세스와 스레드.md
Labels: 민혁, 운영체제

#40 [운영체제] 메모리.md
  운영체제/메모리.md
Labels: 성열, 운영체제

#44 [운영체제] 페이징과 세그먼테이션
  운영체제/images/페이징과_세그먼테이션/매핑테이블.png
  운영체제/images/페이징과_세그먼테이션/세그먼테이션구현.png
  운영체제/images/페이징과_세그먼테이션/세그먼테이션주소변환.png
  운영체제/images/페이징과_세그먼테이션/페이징구현.png
  운영체제/images/페이징과_세그먼테이션/페이징정형화.png
  운영체제/images/페이징과_세그먼테이션/페이징주소변환.png
  운영체제/페이징과 세그먼테이션.md
Labels: 지영, 운영체제

#41 [운영체제] 메모리
  운영체제/메모리.md
Labels: 성열, 운영체제

#38 [운영체제] 세마포어와 뮤텍스
  운영체제/images/뮤텍스 사진1.png
  운영체제/images/뮤텍스 사진2.png
  운영체제/images/뮤텍스 설명.png
  운영체제/images/세마포어 사진1.png
  운영체제/images/세마포어 사진2.png
  운영체제/images/세마포어 설명.png
  운영체제/세마포어와 뮤텍스.md
Labels: 현수, 운영체제

#43 [운영체제] 페이지 교체 알고리즘
  운영체제/images/페이지 교체 알고리즘/2차 기회 페이지 교체 알고리즘.png
  운영체제/images/페이지 교체 알고리즘/FIFO 페이지 교체 알고리즘.png
  운영체제/images/페이지 교체 알고리즘/LFU페이지 교체 알고리즘.png
  운영체제/images/페이지 교체 알고리즘/NRU 페이지 알고리즘 방식.png
  운영체제/images/페이지 교체 알고리즘/NRU 페이지 알고리즘.png
  운영체제/images/페이지 교체 알고리즘/시계 알고리즘 동작 방식.png
  운영체제/images/페이지 교체 알고리즘/시계 알고리즘 포인터.png
  운영체제/images/페이지 교체 알고리즘/참조 비트 시프트방식.png
  운영체제/images/페이지 교체 알고리즘/참조시프트와 LFU페이지 교체의 차이.png
  운영체제/images/페이지 교체 알고리즘/최적 페이지 교체 알고리즘.png
  운영체제/images/페이지 교체 알고리즘/페이지 접근 시간에 기반한 구현.png
  운영체제/images/페이지 교체 알고리즘/페이지교체알고리즘종류.png
  운영체제/페이지 교체 알고리즘.md
Labels: 민혁, 운영체제

#37 [운영체제] Race Condition (경쟁 상태)
  운영체제/Race_Condition(경쟁상태).md
  운영체제/images/Race_condition/1.png
  운영체제/images/Race_condition/10.png
  운영체제/images/Race_condition/11.png
  운영체제/images/Race_condition/12.png
  운영체제/images/Race_condition/13.png
  운영체제/images/Race_condition/14.png
  운영체제/images/Race_condition/15.png
  운영체제/images/Race_condition/16.png
  운영체제/images/Race_condition/2.png
  운영체제/images/Race_condition/3.png
  운영체제/images/Race_condition/4.png
  운영체제/images/Race_condition/5.png
  운영체제/images/Race_condition/6.png
  운영체제/images/Race_condition/7.png
  운영체제/images/Race_condition/8.png
  운영체제/images/Race_condition/9.png
Labels: 승원, 운영체제
