Repository Gachon-CS-Study/CS-Study, pull requests merged in 2024-11, with the labels that each got.

#102 [소프트웨어 엔지니어링] 함수형 프로그래밍
  소프트웨어 엔지니어링/images/함수형 프로그래밍/함수형프로그래밍.png
  소프트웨어 엔지니어링/함수형 프로그래밍.md
Labels: 민혁, 소프트웨어 엔지니어링

#100 [소프트웨어 엔지니어링] 애자일
  소프트웨어 엔지니어링/images/애자일/애자일1.png
  소프트웨어 엔지니어링/애자일.md
Labels: 현수, 소프트웨어 엔지니어링

#99 [소프트웨어 엔지니어링] DevOps
  소프트웨어 엔지니어링/DevOps.md
  소프트웨어 엔지니어링/images/DevOps/image-1.png
  소프트웨어 엔지니어링/images/DevOps/image.png
Labels: 승원, 소프트웨어 엔지니어링

#98 [소프트웨어 엔지니어링] 3rd Party
  소프트웨어 엔지니어링/3rd Party.md
Labels: 지영, 소프트웨어 엔지니어링

#95 [소프트웨어 엔지니어링] 객체지향 프로그래밍
  소프트웨어 인지니어링/객체지향 프로그래밍.md
Labels: 성열, 소프트웨어 엔지니어링

#108 [자료구조] 힙
  자료구조/트라이.md
  자료구조/힙.md
Labels: 성열, 자료구조

#105 [자료구조] 트리
  자료구조/images/hash/image-1.png
  자료구조/images/hash/image-2.png
  자료구조/images/hash/image-3.png
  자료구조/images/hash/image.png
  자료구조/images/tree/image-1.png
  자료구조/images/tree/image-2.png
  자료구조/images/tree/image-3.png
  자료구조/images/tree/image-4.png
  자료구조/images/tree/image-5.png
  자료구조/images/tree/image-6.png
  자료구조/images/tree/image.png
  자료구조/트리.md
  자료구조/해시.md
Labels: 승원, 자료구조

#111 [자료구조] 연결리스트(Linked List) & [소프트웨어 엔지니어링] MSA
  소프트웨어 엔지니어링/MSA.md
  자료구조/연결리스트(LinkedList).md
  자료구조/이진탐색트리.md
Labels: 지원, 소프트웨어 엔지니어링, 자료구조

#112 [자료구조] 배열
  자료구조/배열.md
Labels: 민혁, 자료구조

#113 [자료구조] 스택 & 큐
  자료구조/images/스택 & 큐/선형 큐.png
  자료구조/images/스택 & 큐/원형 큐.png
  자료구조/스택 & 큐.md
Labels: 현수, 자료구조
