Repository Gachon-CS-Study/CS-Study, pull requests merged in 2024-10, with the labels that each got.

#56 [네트워크] TCP 3 & 4 way handshake
  네트워크/TCP 3 & 4 way handshake.md
Labels: 지원, 네트워크

#55 [네트워크] HTTP & HTTPS
  네트워크/HTTP&HTTPS.md
  네트워크/images/HTTP&HTTPS/OAuth작동방식.png
  네트워크/images/HTTP&HTTPS/세션작동방식.png
  네트워크/images/HTTP&HTTPS/쿠키작동방식.png
Labels: 지영, 네트워크

#54 [네트워크] OSI 7계층
  네트워크/OSI 7계층.md
Labels: 성열, 네트워크

#51 [네트워크] UDP
  네트워크/UDP.md
  네트워크/images/UDP/UDP 데이터 전송 방식.png
  네트워크/images/UDP/UDP 헤더 구조.png
Labels: 민혁, 네트워크

#50 [네트워크] TCP/IP (흐름제어/혼잡제어)
  네트워크/TCP&IP_(흐름제어&혼잡제어).md
  네트워크/images/1.png
  네트워크/images/2.png
  네트워크/images/3.png
  네트워크/images/4.png
Labels: 승원, 네트워크

#69 [데이터베이스] 키(Key)
  데이터베이스/images/Key/Key의종류.png
  데이터베이스/images/Key/관계데이터모델.png
  데이터베이스/images/Key/기본용어.png
  데이터베이스/images/Key/기본용어2.png
  데이터베이스/images/Key/기본키.png
  데이터베이스/images/Key/대체키.png
  데이터베이스/images/Key/슈퍼키.png
  데이터베이스/images/Key/외래키.png
  데이터베이스/images/Key/외래키2.png
  데이터베이스/images/Key/후보키.png
  데이터베이스/키(Key).md
Labels: 지영, 데이터베이스

#68 [네트워크] Blocking&Non-blocking io
  네트워크/Blocking&Non-blocking io.md
Labels: 성열, 네트워크

#66 [네트워크] 로드 밸런싱(Load Balancing)
  네트워크/로드 밸런싱(Load Balancing).md
Labels: 지원, 네트워크

#65 [데이터베이스] JOIN
  데이터베이스/JOIN.md
  데이터베이스/images/join/CrossJoin.png
  데이터베이스/images/join/FullOuterJoin.png
  데이터베이스/images/join/INNERJOIN.png
  데이터베이스/images/join/JOIN전체그림.png
  데이터베이스/images/join/address.png
  데이터베이스/images/join/crossjoinsql.png
  데이터베이스/images/join/fulljoinsql.png
  데이터베이스/images/join/innerjoinsql.png
  데이터베이스/images/join/leftOuterJoin.png
  데이터베이스/images/join/leftjoinsql.png
  데이터베이스/images/join/person.png
  데이터베이스/images/join/rightOuterJoin.png
  데이터베이스/images/join/rightjoinsql.png
  데이터베이스/images/join/selfJoin.png
Labels: 민혁, 데이터베이스

#64 [네트워크] TLS/SSL HandShake
  네트워크/TLS_SSL HandShake.md
  네트워크/images/TLS_SSL HandShake.png
Labels: 현수, 네트워크

#61 [네트워크] Blocking/Non-blocking & Synchronous/Asynchronous
  네트워크/Block,NonBlock&Sync,Async.md
  네트워크/images/Block_NonBlock_Sync_Async/image-1.png
  네트워크/images/Block_NonBlock_Sync_Async/image-2.png
  네트워크/images/Block_NonBlock_Sync_Async/image-3.png
  네트워크/images/Block_NonBlock_Sync_Async/image.png
Labels: 승원, 네트워크

#79 [데이터베이스] 이상
  데이터베이스/이상.md
Labels: 성열, 데이터베이스

#77 [데이터베이스] SQL Injection
  데이터베이스/SQL Injection.md
  데이터베이스/images/sql injection 1.png
  데이터베이스/images/sql injection 2.png
Labels: 현수, 데이터베이스

#75 [데이터베이스] 트랜잭션
  데이터베이스/DB 트랜잭션(Transaction).md
  데이터베이스/images/transaction/transactionstatus.png
Labels: 민혁, 데이터베이스

#76 [데이터베이스] 정규화
  데이터베이스/images/정규화/1.png
  데이터베이스/images/정규화/2.png
  데이터베이스/images/정규화/3.png
  데이터베이스/images/정규화/4.png
  데이터베이스/images/정규화/5.png
  데이터베이스/images/정규화/6.png
  데이터베이스/images/정규화/7.png
  데이터베이스/images/정규화/8.png
  데이터베이스/images/정규화/9.png
  데이터베이스/정규화.md
Labels: 지영, 데이터베이스

#73 [데이터베이스] 인덱스
  네트워크/image-3.png
  데이터베이스/images/index/image-1.png
  데이터베이스/images/index/image-2.png
  데이터베이스/images/index/image-3.png
  데이터베이스/images/index/image-4.png
  데이터베이스/images/index/image-5.png
  데이터베이스/images/index/image-6.png
  데이터베이스/images/index/image-7.png
  데이터베이스/images/index/image.png
  데이터베이스/images/transcation_isolation_level/1.png
  데이터베이스/images/transcation_isolation_level/2.png
  데이터베이스/images/transcation_isolation_level/3.png
  데이터베이스/images/transcation_isolation_level/4.png
  데이터베이스/images/transcation_isolation_level/5.png
  데이터베이스/images/transcation_isolation_level/6.png
  데이터베이스/images/transcation_isolation_level/7.png
  데이터베이스/images/transcation_isolation_level/8.png
  데이터베이스/인덱스.md
  데이터베이스/트랜잭션 격리수준.md
Labels: 승원, 데이터베이스
